### ISSUE TITLE
Getting Images Folder Code not clear

### ISSUE THREAD

**Issue by BlueCatSoftware** [CodeBoy722/MediaFacer#18]
```ArrayList<pictureFolderContent> pictureFolders = new ArrayList<>();
      
      pictureFolders.addAll(MediaFacer.withPictureContex(mContext).getPictureFolders());
	
//now load images for the first pictureFolderContent object
	pictureFolders.get(0)
	.setPhotos(MediaFacer
	.withPictureContex(mContext)
	.getAllPictureContentByBucket_id(pictureFolders.get(0).getBucket_id());	
```

It Is not much clear to me cause it throws an exception maybe I'm using it wrongly can you please specify how it can be loaded.

**Comment by CodeBoy722** [comment]
hello @BlueCatSoftware, the method above get a list of empty folders that contain images and iterates each folder to get the associated images in the folder by using the folder's bucket Id  what exception did you get pls I need more info on that too

in version 1.0.3 of MediaFacer there is a new method to get a list of PictureFolder with all the images in 

pictureGet. getAbsolutePictureFolders()

returns an ArrayList of pictureFolderContent with each pictureFolderContent having all pictureContent of the specific folder in it photos variable you don't have to use getAllPictureContentByBucket_id(int bucket_id) to get the images in the folder anymore
