### ISSUE TITLE
FAILED TO RESOLVE com.github.CodeBoy722:MediaFacer:1.0.3

### ISSUE THREAD

**Issue by ketan-waghmare** [CodeBoy722/MediaFacer#3]
Got this error while integrating the library in my project

**Comment by CodeBoy722** [comment]
@ketan-waghmare  did your follow this procedue correctly 

 Add in your your projects root build.gradle file
 allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}   

Add the dependency in the app level build.gradle file
dependencies {
	   implementation 'com.github.CodeBoy722:MediaFacer:1.0.3'
	}

**Comment by ketan-waghmare** [comment]
@CodeBoy722  yes done exactly same as you mentioned in documentation but still it didn't worked for me

**Comment by CodeBoy722** [comment]
@ketan-waghmare  try to clean your project and try again or check your internet before importing the library with gradle, also update your android studio if it not the latest, there is alsolutely no reason why it should not work if you followed the steps in the documentation
