### ISSUE TITLE
Argument for MediaFacer.withAudioContex(?)

### ISSUE THREAD

**Issue by Peeking-Blaster** [CodeBoy722/MediaFacer#8]
In java there is no function called getActivity() as well as in Kotlin, can you please elaborate what this argument should be and how it is supposed to be declared and passed to MediaFacer.withAudioContex(Context) function?
I tried var mContext=ApplicationContext, in Kotlin but the application crashed. I then tried java in hopes of a getActivity() function but no luck.

**Comment by Peeking-Blaster** [comment]
On further investigation I found out that API 23+ got a different Syntax. Now that it is solved I am not able to get the arrayList of audioContent. Would I need to provide some kind of permissions or what? Thanks

**Comment by CodeBoy722** [comment]
hello @Peeking-Blaster  are you using java or kotlin?, MediaFacer is an android library written in java, the function getActivity() which returns a Context, exist only in fragments and not activities if you are calling  MediaFacer.withAudioContex(Context) from an Activity you should use (this) in the place where you put getActivity()

**Comment by CodeBoy722** [comment]
@Peeking-Blaster  yes you should always request the READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions both in your app manifest and also in code with one-time permission api if your app is API 19 and above before using MediaFacer to do any actions on the ContentResolver.

All of  this is done in the MediaFacer Examples project, you should check that
