### ISSUE TITLE
Scan hidden folders that start with a dot?

### ISSUE THREAD

**Issue by AbreuY** [CodeBoy722/MediaFacer#9]
Is it possible to do this using mediastore?  Scan folders that the name starts in this way: .hiddenfolder. 

Or these folders are not added to the MediaStore database?

**Comment by CodeBoy722** [comment]
hello @AbreuY, yes it possible to scan for hidden files with the MediaStore but that functionality is not yet in MediaFacer, I will think about that in the next update
